### ISSUE TITLE
Fix SendGrid error

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#10]
```
Traceback (most recent call last):
  File "/app/opwen_email_server/services/sendgrid.py", line 51, in _send_email
    response = self._client.client.mail.send.post(request_body=request)
  File "/usr/lib/python3.6/site-packages/python_http_client/client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "/usr/lib/python3.6/site-packages/python_http_client/client.py", line 157, in _make_request
    return opener.open(request)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

**Comment by c-w** [comment]
Potential fix: https://www.python.org/dev/peps/pep-0476/

**Comment by c-w** [comment]
Potential fix: https://stackoverflow.com/a/36205876

**Comment by c-w** [comment]
Fix from https://github.com/ascoderu/opwen-cloudserver/commit/63e97c18953c37e7393105d375a1e255a2b28b6f verified and deployed in [release 0.1.18](https://github.com/ascoderu/opwen-cloudserver/releases/tag/0.1.18).
